const MONGO_URI = ""; // MongoDB URI
const ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:5000"; // allowed origins for CORS
const PORT = 5000; // port for the server
const ACCESS_TOKEN_SECRET = ""; // secret for access token
const REFRESH_TOKEN_SECRET = ""; // secret for refresh token
const SD_CHAT_SUPPORT_EMAIL = ""; // email for support
const APP_EMAIL = ""; // email for sending emails to users
const APP_EMAIL_PASSWORD = ""; // password for the email
const NODE_ENV = "development"; // if in production, set to "production"
const CLOUDINARY_CLOUD_NAME = ""; // cloudinary cloud name
const CLOUDINARY_API_KEY = ""; // cloudinary api key
const CLOUDINARY_API_SECRET = ""; // cloudinary api secret
